import type { Metadata } from "next";
import Header from "./components/header";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Box } from "@mui/material";
import "../styles/reset.css";
import "../styles/globals.css";
import { ThemeProvider } from "next-themes";
import { ThemeProvider as MuiThemeProvider } from "@mui/material/styles";
import theme from "../styles/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
          <MuiThemeProvider theme={theme}>
            <AppRouterCacheProvider>
              <Box sx={{ width: "100vw", height: "100vh" }}>
                <Header />
                {children}
              </Box>
            </AppRouterCacheProvider>
          </MuiThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
